[project]
name = "content-generation"
version = "0.1.0"
description = "Voice cards content generation tools"
requires-python = ">=3.11"
dependencies = [
    "openai>=1.0.0",
    "httpx>=0.25.0", 
    "python-dotenv>=1.0.0",
    "google-cloud-texttospeech>=2.14.0"
]
